#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'strscan'

module CSVPlusPlus
  class ModifierParser < Racc::Parser

module_eval(<<'...end modifier.y/module_eval...', 'modifier.y', 47)
  attr_accessor :variables

  def parse(text)
    tokens = []
    @modifiers = []
    @row_level = false

    s = StringScanner.new text
    until s.empty?
      case
      when s.scan(/\s+/)
      when s.scan(/\[\[/)  
        tokens << [:START_CELL_MODIFIERS, s.matched]
      when s.scan(/\!\[\[/)  
        tokens << [:START_ROW_MODIFIERS, s.matched]
      when s.scan(/\]\]/)  
        tokens << [:END_MODIFIERS, s.matched]
      when s.scan(/\w+/)
        tokens << [s.matched, s.matched]
      when s.scan(/-?\d+/)
        tokens << [:INTEGER, s.matched]
      when s.scan(/\//) 
        tokens << [:MODIFIER_SEPARATOR, s.matched]
      else
        raise "Unable to parse starting at: <#{s.peek 100}>"
      end 
    end
    return @modifiers if tokens.empty?

    define_singleton_method(:next_token) { tokens.shift }

    do_parse
 
    # XXX instantiate modifiers
    @modifiers, @row_level
  end
...end modifier.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    28,    29,    30,    31,    32,    21,    22,    23,    24,    21,
    22,    23,    24,    36,     4,    31,    32,     7,     8,     9,
     7,     8,     9,    12,    17,    13,    13,     7,     8,     9,
    28,    38,    30,   -23,    11,   -23,     3,     2,    14,    15,
    16,    33 ]

racc_action_check = [
    15,    15,    15,    15,    15,    14,    14,    14,    14,    19,
    19,    19,    19,    26,     1,    26,    26,     2,     2,     2,
     3,     3,     3,     5,    10,     5,    10,    13,    13,    13,
    27,    27,    27,    29,     4,    29,     0,     0,     7,     8,
     9,    16 ]

racc_action_pointer = [
    32,    14,     7,    10,    34,    17,   nil,    36,    37,    38,
    18,   nil,   nil,    17,    -8,   -17,    32,   nil,   nil,    -4,
   nil,   nil,   nil,   nil,   nil,   nil,    -5,    13,   nil,    16,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -25,   -25,   -25,   -25,   -25,   -25,    -4,   -25,   -25,    -8,
   -25,    39,    -1,   -25,   -25,   -25,   -25,    -2,    -3,    -5,
   -10,   -11,   -12,   -13,   -14,    -6,   -17,   -18,   -19,   -20,
   -21,   -22,   -24,    -7,    -9,   -15,   -23,   -16,   -20 ]

racc_goto_table = [
    26,    20,    27,     5,    10,     1,    34,    18,    19,    25,
   nil,   nil,    37,    35 ]

racc_goto_check = [
     7,     6,     8,     2,     2,     1,     6,     3,     4,     5,
   nil,   nil,     7,     8 ]

racc_goto_pointer = [
   nil,     5,     1,    -6,    -6,    -6,   -13,   -15,   -13 ]

racc_goto_default = [
   nil,   nil,   nil,     6,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 23, :_reduce_none,
  3, 23, :_reduce_none,
  3, 24, :_reduce_none,
  1, 24, :_reduce_none,
  3, 25, :_reduce_none,
  3, 25, :_reduce_none,
  3, 25, :_reduce_none,
  1, 25, :_reduce_none,
  2, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  1, 28, :_reduce_none,
  2, 27, :_reduce_none,
  2, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 27, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none,
  1, 30, :_reduce_none ]

racc_reduce_n = 25

racc_shift_n = 39

racc_token_table = {
  false => 0,
  :error => 1,
  "=" => 2,
  "/" => 3,
  :START_CELL_MODIFIERS => 4,
  :START_ROW_MODIFIERS => 5,
  :END_MODIFIERS => 6,
  :MODIFIER_ID => 7,
  :MODIFIER_SEPARATOR => 8,
  :INTEGER => 9,
  "format" => 10,
  "align" => 11,
  "expand" => 12,
  "bold" => 13,
  "italic" => 14,
  "strikethrough" => 15,
  "underline" => 16,
  "left" => 17,
  "center" => 18,
  "right" => 19,
  "top" => 20,
  "bottom" => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"=\"",
  "\"/\"",
  "START_CELL_MODIFIERS",
  "START_ROW_MODIFIERS",
  "END_MODIFIERS",
  "MODIFIER_ID",
  "MODIFIER_SEPARATOR",
  "INTEGER",
  "\"format\"",
  "\"align\"",
  "\"expand\"",
  "\"bold\"",
  "\"italic\"",
  "\"strikethrough\"",
  "\"underline\"",
  "\"left\"",
  "\"center\"",
  "\"right\"",
  "\"top\"",
  "\"bottom\"",
  "$start",
  "modifiers_definition",
  "modifiers",
  "modifier",
  "format_options",
  "align_options",
  "format_option",
  "halign_options",
  "valign_options" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class ModifierParser
end   # module CSVPlusPlus
