#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'strscan'
require_relative 'modifier'

module CSVPlusPlus
  class ModifierParser < Racc::Parser

module_eval(<<'...end modifier.y/module_eval...', 'modifier.y', 115)
  attr_accessor :cell_modifier, :row_modifier

  def initialize
    @parsing_row = false
  end

  def parsing_row!
    @parsing_row = true
  end

  def finished_row!
    parsing_cell!
  end

  def parsing_cell!
    @parsing_row = false
    @cell_modifier.take_defaults_from!(@row_modifier)
  end

  def freeze!
    (@parsing_row ? @row_modifier : @cell_modifier).freeze!
  end

  def s!(property, value)
    target = @parsing_row ? @row_modifier : @cell_modifier
    target.public_send("#{property}=".to_sym, value)
  end

  def parse(text, cell_modifier:, row_modifier:, row_number: nil, cell_number: nil)
    if text.nil? || !(text.strip.start_with?("[[") || text.start_with?("![["))
      cell_modifier.take_defaults_from!(row_modifier)
      return text
    end

    @cell_modifier = cell_modifier
    @row_modifier = row_modifier

    tokens, value_without_modifier = [], ''
    s = StringScanner.new text
    until s.empty?
      case
      when s.scan(/\s+/)
      when s.scan(/\[\[/)
        tokens << [:START_CELL_MODIFIERS, s.matched]
      when s.scan(/\!\[\[/)
        tokens << [:START_ROW_MODIFIERS, s.matched]
      when s.scan(/\]\]/)
        # XXX we need to keep going if there are two modifiers
        tokens << [:END_MODIFIERS, s.matched]
        value_without_modifier = s.rest
        break
      when s.scan(/\#[a-fA-F0-9]{3,6};?/)
        tokens << [:HEX_COLOR, s.matched]
      when s.scan(/(['\w]+\!)?[\w\d]+:[\w\d]+/)
        tokens << [:A1_NOTATION, s.matched]
      when s.scan(/=/)
        tokens << [s.matched, s.matched]
      when s.scan(/-?\d+/)
        tokens << [:INTEGER, s.matched]
      when s.scan(/'(?:[^'\\]|\\(?:['\\\/bfnrt]|u[0-9a-fA-F]{4}))*'/)
        tokens << [:STRING, s.matched.gsub(/^'|'$/, '')]
      when s.scan(/\//) 
        tokens << [:MODIFIER_SEPARATOR, s.matched]
      when s.scan(/\w+/)
        tokens << [s.matched, s.matched]
      else
        raise SyntaxError.new("Unable to parse starting at", s.peek(100),
                  row_number:, cell_number:,)
      end
    end

    define_singleton_method(:next_token) { tokens.shift }

    begin
      do_parse
    rescue Racc::ParseError => e
      raise SyntaxError.new("Error parsing modifier", e.message, 
                        wrapped_error: e, row_number:, cell_number:,)
    end

    value_without_modifier
  end
...end modifier.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   120,    13,    14,    15,    16,    17,    18,    19,    20,    21,
    22,    23,    24,    25,    26,    27,    13,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,     5,     4,    87,    88,    90,    91,    92,    93,    94,
    95,    96,    97,    98,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   111,   112,   113,   114,   115,
   116,   117,   118,   119,   121,   122,   123,   124,   125,   126,
    13,    14,    15,    16,    17,    18,    19,    20,    21,    22,
    23,    24,    25,    26,    27,    64,    64,    64,    50,   130,
    52,    63,    63,    63,    60,     6,    59,    58,    61,    57,
    66,    67,    68,    69,    70,    71,    60,     5,    59,    58,
    61,    57,   121,   122,   123,   124,   125,   126,   121,   122,
   123,   124,   125,   126,    29,    45,    10,    31,    30,    30,
    50,    51,    52,    53,    54,    80,    81,    82,    83,   128,
    32,    53,    54,    80,    81,    82,    83,   -42,    33,   -42,
    34,    35,    36,    37,    38,    39,    40,    41,    42,    43,
    44,    73,    74,    76,    77,    84,    85,   133,   134,   135,
   136,   137,   138,   139,   140,   141,   142,   143,   144,   145,
   146,   147,   148,   149,   150,   151,   152,   153,   154,   155,
   156,   157,   158,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   179,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120 ]

racc_action_check = [
    44,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,     8,     8,     8,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     0,     0,    44,    44,    44,    44,    44,    44,    44,
    44,    44,    44,    44,    44,    44,    44,    44,    44,    44,
    44,    44,    44,    44,    44,    44,    44,    44,    44,    44,
    44,    44,    44,    44,    44,    44,    44,    44,    44,    44,
    30,    30,    30,    30,    30,    30,    30,    30,    30,    30,
    30,    30,    30,    30,    30,    33,    35,    38,    49,    49,
    49,    33,    35,    38,    32,     1,    32,    32,    32,    32,
    34,    34,    34,    34,    34,    34,    55,     2,    55,    55,
    55,    55,   135,   135,   135,   135,   135,   135,   136,   136,
   136,   136,   136,   136,    11,    28,     6,    13,    11,    28,
    31,    31,    31,    31,    31,    41,    41,    41,    41,    48,
    14,    48,    48,    78,    78,    78,    78,    51,    15,    51,
    16,    17,    18,    19,    20,    21,    22,    23,    25,    26,
    27,    36,    37,    39,    40,    42,    43,    88,    90,    91,
    92,    93,    94,    96,    97,    98,   100,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   111,   112,   113,   114,
   117,   118,   119,   133,   134,   137,   138,   139,   140,   141,
   142,   143,   144,   145,   146,   147,   148,   149,   150,   151,
   152,   153,   154,   155,   156,   157,   158,   163,   165,   166,
   170,   176,   178,   184 ]

racc_action_pointer = [
    20,    95,    96,   nil,   nil,   nil,   126,   nil,   -14,     1,
   nil,   118,   nil,   124,   137,   145,   147,   148,   149,   150,
   151,   152,   153,   154,   nil,   155,   156,   157,   119,   nil,
    55,    96,    60,    78,    60,    79,   153,   149,    80,   150,
   156,   105,   152,   153,   -13,   nil,   nil,   nil,   104,    54,
   nil,   113,   nil,   nil,   nil,    72,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   113,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   165,   nil,
   166,   167,   168,   169,   170,   nil,   171,   172,   173,   nil,
   174,   nil,   175,   176,   177,   178,   179,   180,   181,   182,
   183,   184,   185,   186,   187,   nil,   nil,   188,   189,   190,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   180,   181,    35,    41,   182,   183,   184,
   185,   186,   187,   188,   189,   190,   191,   192,   193,   194,
   195,   196,   205,   198,   199,   200,   201,   202,   203,   nil,
   nil,   nil,   nil,   204,   nil,   205,   206,   nil,   nil,   nil,
   207,   nil,   nil,   nil,   nil,   nil,   208,   nil,   209,   nil,
   nil,   nil,   nil,   nil,   210,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_action_default = [
  -102,  -102,    -2,    -3,    -4,    -6,  -102,    -1,  -102,  -102,
   191,  -102,    -9,  -102,  -102,  -102,  -102,  -102,   -16,  -102,
  -102,  -102,  -102,  -102,   -22,  -102,  -102,  -102,  -102,    -5,
  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,
  -102,  -102,  -102,  -102,  -102,    -7,    -8,   -10,   -36,   -37,
   -38,   -39,   -40,   -41,   -43,   -11,   -45,   -46,   -47,   -48,
   -49,   -50,   -12,   -26,   -27,   -13,   -51,   -52,   -53,   -54,
   -55,   -56,   -14,   -15,   -17,   -18,   -19,   -20,   -21,   -29,
   -30,   -31,   -32,   -33,   -23,   -24,   -25,   -57,   -58,   -61,
  -102,  -102,  -102,  -102,  -102,   -67,  -102,  -102,  -102,   -71,
  -102,   -74,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,
  -102,  -102,  -102,  -102,  -102,   -88,   -89,  -102,  -102,  -102,
   -95,   -96,   -97,   -98,   -99,  -100,  -101,   -34,   -42,   -35,
   -39,   -44,   -28,  -102,  -102,  -102,  -102,  -102,  -102,  -102,
  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,
  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,  -102,   -59,
   -62,   -63,   -64,  -102,   -66,  -102,   -69,   -94,   -70,   -72,
  -102,   -76,   -77,   -78,   -79,   -80,  -102,   -82,   -83,   -84,
   -85,   -86,   -87,   -90,   -91,   -92,   -65,   -68,   -93,   -75,
   -81 ]

racc_goto_table = [
    89,    79,    56,    48,     1,    49,   166,    62,     3,    72,
     7,     2,    75,    11,    28,     8,    99,   178,     9,    46,
    47,   129,   127,   184,    55,   131,    65,    78,    86,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   132,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   159,
   160,   nil,   nil,   163,   164,   165,   nil,   168,   169,   170,
   171,   172,   173,   174,   175,   176,   177,   161,   162,   180,
   181,   182,   183,   nil,   185,   nil,   nil,   nil,   nil,   186,
   nil,   187,   188,   nil,   nil,   nil,   189,   nil,   nil,   nil,
   nil,   nil,   190,   nil,   188,   nil,   nil,   nil,   nil,   nil,
   188 ]

racc_goto_check = [
    18,    14,    17,    15,     1,    16,    20,    10,     3,    10,
     3,     2,    10,     4,     4,     5,    19,    20,     6,     7,
     8,    15,    16,    20,     9,    17,    11,    12,    13,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,
    18,   nil,   nil,    18,    18,    18,   nil,    18,    18,    18,
    18,    18,    18,    18,    18,    18,    18,    19,    19,    18,
    18,    18,    18,   nil,    18,   nil,   nil,   nil,   nil,    18,
   nil,    18,    18,   nil,   nil,   nil,    18,   nil,   nil,   nil,
   nil,   nil,    18,   nil,    18,   nil,   nil,   nil,   nil,   nil,
    18 ]

racc_goto_pointer = [
   nil,     4,    11,     8,     5,    11,    13,   -11,   -11,    -8,
   -26,    -8,   -14,   -16,   -40,   -28,   -26,   -30,   -44,   -28,
  -134 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   167,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 84, :_reduce_none,
  1, 84, :_reduce_none,
  1, 84, :_reduce_none,
  0, 88, :_reduce_4,
  4, 85, :_reduce_5,
  0, 89, :_reduce_6,
  4, 86, :_reduce_none,
  3, 87, :_reduce_none,
  1, 87, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_12,
  3, 90, :_reduce_13,
  3, 90, :_reduce_14,
  3, 90, :_reduce_15,
  1, 90, :_reduce_16,
  3, 90, :_reduce_17,
  3, 90, :_reduce_18,
  3, 90, :_reduce_19,
  3, 90, :_reduce_20,
  3, 90, :_reduce_none,
  1, 90, :_reduce_22,
  3, 90, :_reduce_23,
  3, 90, :_reduce_24,
  3, 90, :_reduce_25,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  2, 95, :_reduce_none,
  1, 95, :_reduce_29,
  1, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 97, :_reduce_none,
  2, 91, :_reduce_34,
  2, 91, :_reduce_35,
  1, 91, :_reduce_36,
  1, 91, :_reduce_37,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 98, :_reduce_none,
  1, 99, :_reduce_none,
  1, 99, :_reduce_none,
  1, 99, :_reduce_none,
  2, 92, :_reduce_none,
  1, 92, :_reduce_45,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  1, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  4, 96, :_reduce_none,
  3, 96, :_reduce_none,
  1, 96, :_reduce_none,
  4, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  1, 96, :_reduce_none,
  3, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  4, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  4, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  3, 96, :_reduce_none,
  2, 103, :_reduce_none,
  1, 103, :_reduce_none,
  1, 101, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none,
  1, 102, :_reduce_none ]

racc_reduce_n = 102

racc_shift_n = 191

racc_token_table = {
  false => 0,
  :error => 1,
  ":" => 2,
  "=" => 3,
  "/" => 4,
  :A1_NOTATION => 5,
  :END_MODIFIERS => 6,
  :HEX_COLOR => 7,
  :INTEGER => 8,
  :MODIFIER_ID => 9,
  :MODIFIER_SEPARATOR => 10,
  :START_CELL_MODIFIERS => 11,
  :START_ROW_MODIFIERS => 12,
  :STRING => 13,
  :URL => 14,
  "align" => 15,
  "border" => 16,
  "bordercolor" => 17,
  "borderstyle" => 18,
  "color" => 19,
  "expand" => 20,
  "font" => 21,
  "fontcolor" => 22,
  "fontfamily" => 23,
  "fontsize" => 24,
  "format" => 25,
  "freeze" => 26,
  "hyperlink" => 27,
  "note" => 28,
  "validate" => 29,
  "bold" => 30,
  "italic" => 31,
  "strikethrough" => 32,
  "underline" => 33,
  "left" => 34,
  "center" => 35,
  "right" => 36,
  "top" => 37,
  "bottom" => 38,
  "all" => 39,
  "dashed" => 40,
  "dotted" => 41,
  "double" => 42,
  "solid" => 43,
  "solid_medium" => 44,
  "solid_thick" => 45,
  "blank" => 46,
  "boolean" => 47,
  "custom_formula" => 48,
  "date_after" => 49,
  "date_before" => 50,
  "date_between" => 51,
  "date_eq" => 52,
  "date_is_valid" => 53,
  "date_not_between" => 54,
  "date_not_eq" => 55,
  "date_on_or_after" => 56,
  "date_on_or_before" => 57,
  "not_blank" => 58,
  "number_between" => 59,
  "number_eq" => 60,
  "number_greater" => 61,
  "number_greater_than_eq" => 62,
  "number_less" => 63,
  "number_less_than_eq" => 64,
  "number_not_between" => 65,
  "number_not_eq" => 66,
  "one_of_list" => 67,
  "one_of_range" => 68,
  "text_contains" => 69,
  "text_ends_with" => 70,
  "text_eq" => 71,
  "text_is_email" => 72,
  "text_is_url" => 73,
  "text_not_contains" => 74,
  "text_not_eq" => 75,
  "text_starts_with" => 76,
  "past_year" => 77,
  "past_month" => 78,
  "past_week" => 79,
  "yesterday" => 80,
  "today" => 81,
  "tomorrow" => 82 }

racc_nt_base = 83

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\":\"",
  "\"=\"",
  "\"/\"",
  "A1_NOTATION",
  "END_MODIFIERS",
  "HEX_COLOR",
  "INTEGER",
  "MODIFIER_ID",
  "MODIFIER_SEPARATOR",
  "START_CELL_MODIFIERS",
  "START_ROW_MODIFIERS",
  "STRING",
  "URL",
  "\"align\"",
  "\"border\"",
  "\"bordercolor\"",
  "\"borderstyle\"",
  "\"color\"",
  "\"expand\"",
  "\"font\"",
  "\"fontcolor\"",
  "\"fontfamily\"",
  "\"fontsize\"",
  "\"format\"",
  "\"freeze\"",
  "\"hyperlink\"",
  "\"note\"",
  "\"validate\"",
  "\"bold\"",
  "\"italic\"",
  "\"strikethrough\"",
  "\"underline\"",
  "\"left\"",
  "\"center\"",
  "\"right\"",
  "\"top\"",
  "\"bottom\"",
  "\"all\"",
  "\"dashed\"",
  "\"dotted\"",
  "\"double\"",
  "\"solid\"",
  "\"solid_medium\"",
  "\"solid_thick\"",
  "\"blank\"",
  "\"boolean\"",
  "\"custom_formula\"",
  "\"date_after\"",
  "\"date_before\"",
  "\"date_between\"",
  "\"date_eq\"",
  "\"date_is_valid\"",
  "\"date_not_between\"",
  "\"date_not_eq\"",
  "\"date_on_or_after\"",
  "\"date_on_or_before\"",
  "\"not_blank\"",
  "\"number_between\"",
  "\"number_eq\"",
  "\"number_greater\"",
  "\"number_greater_than_eq\"",
  "\"number_less\"",
  "\"number_less_than_eq\"",
  "\"number_not_between\"",
  "\"number_not_eq\"",
  "\"one_of_list\"",
  "\"one_of_range\"",
  "\"text_contains\"",
  "\"text_ends_with\"",
  "\"text_eq\"",
  "\"text_is_email\"",
  "\"text_is_url\"",
  "\"text_not_contains\"",
  "\"text_not_eq\"",
  "\"text_starts_with\"",
  "\"past_year\"",
  "\"past_month\"",
  "\"past_week\"",
  "\"yesterday\"",
  "\"today\"",
  "\"tomorrow\"",
  "$start",
  "modifiers_definition",
  "row_modifiers",
  "cell_modifiers",
  "modifiers",
  "@1",
  "@2",
  "modifier",
  "align_options",
  "border_options",
  "color",
  "borderstyle_option",
  "format_options",
  "condition",
  "format_option",
  "halign_option",
  "valign_option",
  "border_option",
  "condition_value",
  "relative_date",
  "condition_values" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'modifier.y', 23)
  def _reduce_4(val, _values, result)
     parsing_row!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 25)
  def _reduce_5(val, _values, result)
     finished_row!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 27)
  def _reduce_6(val, _values, result)
     parsing_cell!
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'modifier.y', 35)
  def _reduce_12(val, _values, result)
     s!(:bordercolor, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 36)
  def _reduce_13(val, _values, result)
     s!(:borderstyle, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 37)
  def _reduce_14(val, _values, result)
     s!(:color, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 38)
  def _reduce_15(val, _values, result)
     s!(:expand, Modifier::Expand.new(val[2].to_i))
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 39)
  def _reduce_16(val, _values, result)
     s!(:expand, Modifier::Expand.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 40)
  def _reduce_17(val, _values, result)
     s!(:fontfamily, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 41)
  def _reduce_18(val, _values, result)
     s!(:fontcolor, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 42)
  def _reduce_19(val, _values, result)
     s!(:fontfamily, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 43)
  def _reduce_20(val, _values, result)
     s!(:fontsize, val[2].to_f)
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'modifier.y', 45)
  def _reduce_22(val, _values, result)
     freeze!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 46)
  def _reduce_23(val, _values, result)
     s!(:hyperlink, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 47)
  def _reduce_24(val, _values, result)
     s!(:note, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 48)
  def _reduce_25(val, _values, result)
     s!(:validation, val[2])
    result
  end
.,.,

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'modifier.y', 52)
  def _reduce_29(val, _values, result)
     s!(:format, val[0])
    result
  end
.,.,

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

module_eval(<<'.,.,', 'modifier.y', 55)
  def _reduce_34(val, _values, result)
     s!(:align, val[0]); s!(:align, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 56)
  def _reduce_35(val, _values, result)
     s!(:align, val[0]); s!(:align, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 57)
  def _reduce_36(val, _values, result)
     s!(:align, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 58)
  def _reduce_37(val, _values, result)
     s!(:align, val[0])
    result
  end
.,.,

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

module_eval(<<'.,.,', 'modifier.y', 63)
  def _reduce_45(val, _values, result)
     s!(:border, val[0])
    result
  end
.,.,

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

# reduce 93 omitted

# reduce 94 omitted

# reduce 95 omitted

# reduce 96 omitted

# reduce 97 omitted

# reduce 98 omitted

# reduce 99 omitted

# reduce 100 omitted

# reduce 101 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class ModifierParser
end   # module CSVPlusPlus
