#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'strscan'
require_relative 'modifier'

module CSVPlusPlus
  class ModifierParser < Racc::Parser

module_eval(<<'...end modifier.y/module_eval...', 'modifier.y', 104)
  attr_accessor :cell_modifier, :row_modifier

  def initialize
    @parsing_row = false
  end

  def parsing_row!
    @parsing_row = true
  end

  def parsing_cell!
    @parsing_row = false
  end

  def freeze!
    (@parsing_row ? @row_modifier : @cell_modifier).freeze!
  end

  def s!(property, value)
    target = @parsing_row ? @row_modifier : @cell_modifier
    target.public_send("#{property}=".to_sym, value)
  end

  def parse(text, cell_modifier:, row_modifier:, row_number: nil, cell_number: nil)
    return text if text.nil?
    return text unless text.strip.start_with?("[[") || text.start_with?("![[")

    @cell_modifier = cell_modifier
    @row_modifier = row_modifier

    tokens, value_without_modifier = [], ''
    s = StringScanner.new text
    until s.empty?
      case
      when s.scan(/\s+/)
      when s.scan(/\[\[/)
        tokens << [:START_CELL_MODIFIERS, s.matched]
      when s.scan(/\!\[\[/)
        tokens << [:START_ROW_MODIFIERS, s.matched]
      when s.scan(/\]\]/)
        # XXX we need to keep going if there are two modifiers
        tokens << [:END_MODIFIERS, s.matched]
        value_without_modifier = s.rest
        break
      when s.scan(/\#[a-fA-F0-9]{3,6};?/)
        tokens << [:HEX_COLOR, s.matched]
      when s.scan(/(['\w]+\!)?[\w\d]+:[\w\d]+/)
        tokens << [:A1_NOTATION, s.matched]
      when s.scan(/=/)
        tokens << [s.matched, s.matched]
      when s.scan(/-?\d+/)
        tokens << [:INTEGER, s.matched]
      when s.scan(/\w+:\/\/.+/)
        tokens << [:URL, s.matched]
      when s.scan(/\//) 
        tokens << [:MODIFIER_SEPARATOR, s.matched]
      when s.scan(/\w+/)
        tokens << [s.matched, s.matched]
      else
        raise SyntaxError.new("Unable to parse starting at", s.peek(100),
                  row_number:, cell_number:,)
      end
    end

    define_singleton_method(:next_token) { tokens.shift }

    begin
      do_parse
    rescue Racc::ParseError => e
      raise SyntaxError.new("Error parsing modifier", e.message, 
                        wrapped_error: e, row_number:, cell_number:,)
    end

    value_without_modifier
  end
...end modifier.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
   107,    17,    52,     4,    51,    50,    53,    49,     7,    10,
    11,    12,    13,    14,    15,    16,    18,    19,    20,    21,
    22,    55,    56,    57,    58,    59,    60,    42,   117,    44,
    74,    75,    77,    78,    79,    80,    81,    82,    83,    84,
    85,    87,    88,    89,    90,    91,    92,    93,    94,    95,
    96,    97,    98,    99,   100,   101,   102,   103,   104,   105,
   106,   108,   109,   110,   111,   112,   113,    17,    52,    26,
    51,    50,    53,    49,    27,    10,    11,    12,    13,    14,
    15,    16,    18,    19,    20,    21,    22,    17,   108,   109,
   110,   111,   112,   113,    28,    10,    11,    12,    13,    14,
    15,    16,    18,    19,    20,    21,    22,   108,   109,   110,
   111,   112,   113,    24,    37,     3,     2,    25,    25,    42,
    43,    44,    45,    46,    67,    68,    69,    70,   115,    29,
    45,    46,    67,    68,    69,    70,   -35,    30,   -35,    31,
    32,    33,    34,    35,    36,    61,    62,    63,    64,    71,
    72,   120,   121,   122,   123,   124,   125,   126,   127,   128,
   129,   130,   131,   132,   133,   134,   135,   136,   137,   138,
   139,   140,   141,   142,   143,   144,   145,   107,   107,   107,
   107,   107,   107,   107,   107,   107,   107,   107,   107,   107,
   107,   107,   107,   107,   166,   107,   107,   107,   107,   107,
   107,   107,   107,   107,   107,   107,   107,   107 ]

racc_action_check = [
    36,     5,    27,     1,    27,    27,    27,    27,     4,     5,
     5,     5,     5,     5,     5,     5,     5,     5,     5,     5,
     5,    28,    28,    28,    28,    28,    28,    41,    41,    41,
    36,    36,    36,    36,    36,    36,    36,    36,    36,    36,
    36,    36,    36,    36,    36,    36,    36,    36,    36,    36,
    36,    36,    36,    36,    36,    36,    36,    36,    36,    36,
    36,    36,    36,    36,    36,    36,    36,     6,    47,    10,
    47,    47,    47,    47,    11,     6,     6,     6,     6,     6,
     6,     6,     6,     6,     6,     6,     6,    25,   122,   122,
   122,   122,   122,   122,    12,    25,    25,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,   123,   123,   123,
   123,   123,   123,     8,    23,     0,     0,     8,    23,    26,
    26,    26,    26,    26,    33,    33,    33,    33,    40,    13,
    40,    40,    65,    65,    65,    65,    43,    14,    43,    15,
    16,    18,    20,    21,    22,    29,    30,    31,    32,    34,
    35,    75,    77,    78,    79,    80,    81,    83,    84,    85,
    87,    89,    90,    91,    92,    93,    94,    95,    96,    97,
    98,    99,   100,   101,   104,   105,   106,   120,   121,   124,
   125,   126,   127,   128,   129,   130,   131,   132,   133,   134,
   135,   136,   137,   138,   139,   140,   141,   142,   143,   144,
   145,   150,   152,   153,   157,   163,   165,   171 ]

racc_action_pointer = [
   104,     3,   nil,   nil,     8,    -6,    60,   nil,   107,   nil,
    66,    71,    91,   126,   134,   136,   137,   nil,   138,   nil,
   139,   140,   141,   108,   nil,    80,    88,   -29,   -16,   137,
   133,   139,   135,    97,   135,   137,   -13,   nil,   nil,   nil,
    96,    -4,   nil,   105,   nil,   nil,   nil,    37,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   105,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   149,   nil,   150,   151,   152,
   153,   154,   nil,   155,   156,   157,   nil,   158,   nil,   159,
   160,   161,   162,   163,   164,   165,   166,   167,   168,   169,
   170,   171,   nil,   nil,   172,   173,   174,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   164,   165,    14,    33,   166,   167,   168,   169,   170,   171,
   172,   173,   174,   175,   176,   177,   178,   179,   180,   189,
   182,   183,   184,   185,   186,   187,   nil,   nil,   nil,   nil,
   188,   nil,   189,   190,   nil,   nil,   nil,   191,   nil,   nil,
   nil,   nil,   nil,   192,   nil,   193,   nil,   nil,   nil,   nil,
   nil,   194,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -95,   -95,    -1,    -3,   -95,   -95,   -95,   178,   -95,    -6,
   -95,   -95,   -95,   -11,   -95,   -95,   -95,   -15,   -95,   -17,
   -95,   -95,   -95,   -95,    -2,   -95,   -95,   -95,   -95,   -95,
   -95,   -95,   -95,   -95,   -95,   -95,   -95,    -4,    -5,    -7,
   -29,   -30,   -31,   -32,   -33,   -34,   -36,    -8,   -38,   -39,
   -40,   -41,   -42,   -43,    -9,   -44,   -45,   -46,   -47,   -48,
   -49,   -10,   -12,   -13,   -14,   -16,   -22,   -23,   -24,   -25,
   -26,   -18,   -19,   -20,   -50,   -51,   -54,   -95,   -95,   -95,
   -95,   -95,   -60,   -95,   -95,   -95,   -64,   -95,   -67,   -95,
   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,
   -95,   -95,   -81,   -82,   -95,   -95,   -95,   -88,   -89,   -90,
   -91,   -92,   -93,   -94,   -27,   -35,   -28,   -32,   -37,   -21,
   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,
   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,   -95,
   -95,   -95,   -95,   -95,   -95,   -95,   -52,   -55,   -56,   -57,
   -95,   -59,   -95,   -62,   -87,   -63,   -65,   -95,   -69,   -70,
   -71,   -72,   -73,   -95,   -75,   -76,   -77,   -78,   -79,   -80,
   -83,   -84,   -85,   -58,   -61,   -86,   -68,   -74 ]

racc_goto_table = [
    76,    66,    48,   153,    40,     8,    23,    41,     1,     5,
     6,    38,    39,    47,   165,    54,    86,    65,    73,   116,
   171,   114,   118,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   119,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   146,   147,   nil,   nil,   150,   151,
   152,   nil,   155,   156,   157,   158,   159,   160,   161,   162,
   163,   164,   148,   149,   167,   168,   169,   170,   nil,   172,
   nil,   nil,   nil,   nil,   173,   nil,   174,   175,   nil,   nil,
   nil,   176,   nil,   nil,   nil,   nil,   nil,   177,   nil,   175,
   nil,   nil,   nil,   nil,   nil,   175 ]

racc_goto_check = [
    15,    11,    14,    17,    12,     2,     2,    13,     1,     3,
     4,     5,     6,     7,    17,     8,    16,     9,    10,    12,
    17,    13,    14,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    11,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    15,    15,   nil,   nil,    15,    15,
    15,   nil,    15,    15,    15,    15,    15,    15,    15,    15,
    15,    15,    16,    16,    15,    15,    15,    15,   nil,    15,
   nil,   nil,   nil,   nil,    15,   nil,    15,    15,   nil,   nil,
   nil,    15,   nil,   nil,   nil,   nil,   nil,    15,   nil,    15,
   nil,   nil,   nil,   nil,   nil,    15 ]

racc_goto_pointer = [
   nil,     8,     0,     7,     7,   -14,   -14,   -14,   -13,   -16,
   -18,   -32,   -22,   -19,   -25,   -36,   -20,  -124 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   154,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 83, :_reduce_1,
  4, 81, :_reduce_none,
  0, 84, :_reduce_3,
  4, 81, :_reduce_none,
  3, 82, :_reduce_none,
  1, 82, :_reduce_none,
  3, 85, :_reduce_none,
  3, 85, :_reduce_none,
  3, 85, :_reduce_9,
  3, 85, :_reduce_10,
  1, 85, :_reduce_11,
  3, 85, :_reduce_12,
  3, 85, :_reduce_13,
  3, 85, :_reduce_none,
  1, 85, :_reduce_15,
  3, 85, :_reduce_none,
  1, 85, :_reduce_17,
  3, 85, :_reduce_18,
  3, 85, :_reduce_19,
  3, 85, :_reduce_20,
  2, 89, :_reduce_none,
  1, 89, :_reduce_22,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  1, 91, :_reduce_none,
  2, 86, :_reduce_27,
  2, 86, :_reduce_28,
  1, 86, :_reduce_29,
  1, 86, :_reduce_30,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 92, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  1, 93, :_reduce_none,
  2, 87, :_reduce_none,
  1, 87, :_reduce_38,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 94, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 88, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  1, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  4, 90, :_reduce_none,
  3, 90, :_reduce_none,
  1, 90, :_reduce_none,
  4, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  1, 90, :_reduce_none,
  3, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  4, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  4, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  1, 90, :_reduce_none,
  1, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  3, 90, :_reduce_none,
  2, 97, :_reduce_none,
  1, 97, :_reduce_none,
  1, 95, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none,
  1, 96, :_reduce_none ]

racc_reduce_n = 95

racc_shift_n = 178

racc_token_table = {
  false => 0,
  :error => 1,
  ":" => 2,
  "=" => 3,
  "/" => 4,
  :A1_NOTATION => 5,
  :END_MODIFIERS => 6,
  :HEX_COLOR => 7,
  :INTEGER => 8,
  :MODIFIER_ID => 9,
  :MODIFIER_SEPARATOR => 10,
  :START_CELL_MODIFIERS => 11,
  :START_ROW_MODIFIERS => 12,
  :STRING => 13,
  :URL => 14,
  "align" => 15,
  "border" => 16,
  "borderstyle" => 17,
  "expand" => 18,
  "font" => 19,
  "fontfamily" => 20,
  "fontcolor" => 21,
  "format" => 22,
  "freeze" => 23,
  "hyperlink" => 24,
  "note" => 25,
  "validate" => 26,
  "bold" => 27,
  "italic" => 28,
  "strikethrough" => 29,
  "underline" => 30,
  "left" => 31,
  "center" => 32,
  "right" => 33,
  "top" => 34,
  "bottom" => 35,
  "all" => 36,
  "dashed" => 37,
  "dotted" => 38,
  "double" => 39,
  "solid" => 40,
  "solid_medium" => 41,
  "solid_thick" => 42,
  "blank" => 43,
  "boolean" => 44,
  "custom_formula" => 45,
  "date_after" => 46,
  "date_before" => 47,
  "date_between" => 48,
  "date_eq" => 49,
  "date_is_valid" => 50,
  "date_not_between" => 51,
  "date_not_eq" => 52,
  "date_on_or_after" => 53,
  "date_on_or_before" => 54,
  "not_blank" => 55,
  "number_between" => 56,
  "number_eq" => 57,
  "number_greater" => 58,
  "number_greater_than_eq" => 59,
  "number_less" => 60,
  "number_less_than_eq" => 61,
  "number_not_between" => 62,
  "number_not_eq" => 63,
  "one_of_list" => 64,
  "one_of_range" => 65,
  "text_contains" => 66,
  "text_ends_with" => 67,
  "text_eq" => 68,
  "text_is_email" => 69,
  "text_is_url" => 70,
  "text_not_contains" => 71,
  "text_not_eq" => 72,
  "text_starts_with" => 73,
  "past_year" => 74,
  "past_month" => 75,
  "past_week" => 76,
  "yesterday" => 77,
  "today" => 78,
  "tomorrow" => 79 }

racc_nt_base = 80

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\":\"",
  "\"=\"",
  "\"/\"",
  "A1_NOTATION",
  "END_MODIFIERS",
  "HEX_COLOR",
  "INTEGER",
  "MODIFIER_ID",
  "MODIFIER_SEPARATOR",
  "START_CELL_MODIFIERS",
  "START_ROW_MODIFIERS",
  "STRING",
  "URL",
  "\"align\"",
  "\"border\"",
  "\"borderstyle\"",
  "\"expand\"",
  "\"font\"",
  "\"fontfamily\"",
  "\"fontcolor\"",
  "\"format\"",
  "\"freeze\"",
  "\"hyperlink\"",
  "\"note\"",
  "\"validate\"",
  "\"bold\"",
  "\"italic\"",
  "\"strikethrough\"",
  "\"underline\"",
  "\"left\"",
  "\"center\"",
  "\"right\"",
  "\"top\"",
  "\"bottom\"",
  "\"all\"",
  "\"dashed\"",
  "\"dotted\"",
  "\"double\"",
  "\"solid\"",
  "\"solid_medium\"",
  "\"solid_thick\"",
  "\"blank\"",
  "\"boolean\"",
  "\"custom_formula\"",
  "\"date_after\"",
  "\"date_before\"",
  "\"date_between\"",
  "\"date_eq\"",
  "\"date_is_valid\"",
  "\"date_not_between\"",
  "\"date_not_eq\"",
  "\"date_on_or_after\"",
  "\"date_on_or_before\"",
  "\"not_blank\"",
  "\"number_between\"",
  "\"number_eq\"",
  "\"number_greater\"",
  "\"number_greater_than_eq\"",
  "\"number_less\"",
  "\"number_less_than_eq\"",
  "\"number_not_between\"",
  "\"number_not_eq\"",
  "\"one_of_list\"",
  "\"one_of_range\"",
  "\"text_contains\"",
  "\"text_ends_with\"",
  "\"text_eq\"",
  "\"text_is_email\"",
  "\"text_is_url\"",
  "\"text_not_contains\"",
  "\"text_not_eq\"",
  "\"text_starts_with\"",
  "\"past_year\"",
  "\"past_month\"",
  "\"past_week\"",
  "\"yesterday\"",
  "\"today\"",
  "\"tomorrow\"",
  "$start",
  "modifiers_definition",
  "modifiers",
  "@1",
  "@2",
  "modifier",
  "align_options",
  "border_options",
  "borderstyle_option",
  "format_options",
  "condition",
  "format_option",
  "halign_option",
  "valign_option",
  "border_option",
  "condition_value",
  "relative_date",
  "condition_values" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'modifier.y', 19)
  def _reduce_1(val, _values, result)
     parsing_row!
    result
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'modifier.y', 22)
  def _reduce_3(val, _values, result)
     parsing_cell!
    result
  end
.,.,

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

module_eval(<<'.,.,', 'modifier.y', 30)
  def _reduce_9(val, _values, result)
     s!(:borderstyle, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 31)
  def _reduce_10(val, _values, result)
     s!(:expand, Modifier::Expand.new(val[2].to_i))
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 32)
  def _reduce_11(val, _values, result)
     s!(:expand, Modifier::Expand.new)
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 33)
  def _reduce_12(val, _values, result)
     s!(:font, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 34)
  def _reduce_13(val, _values, result)
     s!(:fontfamily, val[2])
    result
  end
.,.,

# reduce 14 omitted

module_eval(<<'.,.,', 'modifier.y', 35)
  def _reduce_15(val, _values, result)
     s!(:fontcolor, val[2])
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'modifier.y', 37)
  def _reduce_17(val, _values, result)
     freeze!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 38)
  def _reduce_18(val, _values, result)
     s!(:hyperlink, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 39)
  def _reduce_19(val, _values, result)
     s!(:note, val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 40)
  def _reduce_20(val, _values, result)
     s!(:validation, val[2])
    result
  end
.,.,

# reduce 21 omitted

module_eval(<<'.,.,', 'modifier.y', 42)
  def _reduce_22(val, _values, result)
     s!(:format, val[0])
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

module_eval(<<'.,.,', 'modifier.y', 45)
  def _reduce_27(val, _values, result)
     s!(:align, val[0]); s!(:align, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 46)
  def _reduce_28(val, _values, result)
     s!(:align, val[0]); s!(:align, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 47)
  def _reduce_29(val, _values, result)
     s!(:align, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 48)
  def _reduce_30(val, _values, result)
     s!(:align, val[0])
    result
  end
.,.,

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'modifier.y', 52)
  def _reduce_38(val, _values, result)
     s!(:border, val[0])
    result
  end
.,.,

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

# reduce 60 omitted

# reduce 61 omitted

# reduce 62 omitted

# reduce 63 omitted

# reduce 64 omitted

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

# reduce 71 omitted

# reduce 72 omitted

# reduce 73 omitted

# reduce 74 omitted

# reduce 75 omitted

# reduce 76 omitted

# reduce 77 omitted

# reduce 78 omitted

# reduce 79 omitted

# reduce 80 omitted

# reduce 81 omitted

# reduce 82 omitted

# reduce 83 omitted

# reduce 84 omitted

# reduce 85 omitted

# reduce 86 omitted

# reduce 87 omitted

# reduce 88 omitted

# reduce 89 omitted

# reduce 90 omitted

# reduce 91 omitted

# reduce 92 omitted

# reduce 93 omitted

# reduce 94 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class ModifierParser
end   # module CSVPlusPlus
