#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

require_relative './expand'
require_relative './lexer'

module CSVPlusPlus
  class ModifierParser < Racc::Parser

module_eval(<<'...end modifier.y/module_eval...', 'modifier.y', 60)
  attr_reader :return_value

  include ::CSVPlusPlus::Lexer

  # @param cell_modifier [Modifier]
  # @param row_modifier [Modifier]
  # @param scope [Scope]
  def initialize(cell_modifier:, row_modifier:, scope:)
    super()

    @parsing_row = false
    @cell_modifier = cell_modifier
    @row_modifier = row_modifier
    @scope = scope
  end

  protected

  def anything_to_parse?(input)
    @modifiers_to_parse = input.scan(/!?\[\[/).count

    if @modifiers_to_parse == 0
      assign_defaults!
      @return_value = input
    end

    @modifiers_to_parse > 0
  end

  def parse_subject
    'modifier'
  end

  def tokenizer
    ::CSVPlusPlus::Lexer::Tokenizer.new(
      ignore: /\s+/,
      stop_fn: lambda do |scanner|
        return false unless scanner.scan(/\]\]/)

        @tokens << [:END_MODIFIERS, scanner.matched]
        @return_value = scanner.rest

        @modifiers_to_parse -= 1
        @modifiers_to_parse == 0
      end,
      tokens: [
        [/\bborder\b/, 'border'],
        [/\bbordercolor\b/, 'bordercolor'],
        [/\bborderstyle\b/, 'borderstyle'],
        [/\bcolor\b/, 'color'],
        [/\bexpand\b/, 'expand'],
        [/\bfontcolor\b/, 'fontcolor'],
        [/\bfontfamily\b/, 'fontfamily'],
        [/\bfontsize\b/, 'fontsize'],
        [/\bformat\b/, 'format'],
        [/\bfreeze\b/, 'freeze'],
        [/\bhalign\b/, 'halign'],
        [/\bnote\b/, 'note'],
        [/\bnumberformat\b/, 'numberformat'],
        [/\bvalidate\b/, 'validate'],
        [/\bvalign\b/, 'valign'],
        [/\bvar\b/, 'var'],
        [/\[\[/, :START_CELL_MODIFIERS],
        [/!\[\[/, :START_ROW_MODIFIERS],
        [/=/, :EQ],
        [/-?[\d.]+/, :NUMBER],
        [/'(?:[^'\\]|\\(?:['\\\/bfnrt]|u[0-9a-fA-F]{4}))*'/, :STRING],
        [/\//, :MODIFIER_SEPARATOR],
        TOKEN_LIBRARY[:A1_NOTATION],
        TOKEN_LIBRARY[:HEX_COLOR],
        [/[\w]+/, :WORD],
      ],
      alter_matches: {
        STRING: ->(s) { s.gsub(/^'|'$/, '') }
      },
    )
  end

  private

  def assign_defaults!
    @cell_modifier.take_defaults_from!(@row_modifier)
  end

  def parsing_row!
    @parsing_row = true
  end

  def finished_row!
    parsing_cell!
  end

  def parsing_cell!
    @parsing_row = false
    assign_defaults!
  end

  def define_var(var_id)
    @scope.bind_variable_to_cell(var_id)
    modifier.var = var_id.to_sym
  end

  def modifier
    @parsing_row ? @row_modifier : @cell_modifier
  end
...end modifier.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    13,    14,    15,    16,    17,    18,    19,    20,    21,    22,
    23,    24,    25,    26,    27,    28,    13,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    23,    24,    25,    26,
    27,    28,    13,    14,    15,    16,    17,    18,    19,    20,
    21,    22,    23,    24,    25,    26,    27,    28,    30,    47,
     5,     4,     6,    31,    31,     5,    10,    32,    33,    34,
    35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
    45,    46,    49,    50,    51,    52,    53,    54,    55,    56,
    57,    58,    59,    60,    61,    62,    63 ]

racc_action_check = [
     8,     8,     8,     8,     8,     8,     8,     8,     8,     8,
     8,     8,     8,     8,     8,     8,     9,     9,     9,     9,
     9,     9,     9,     9,     9,     9,     9,     9,     9,     9,
     9,     9,    31,    31,    31,    31,    31,    31,    31,    31,
    31,    31,    31,    31,    31,    31,    31,    31,    11,    29,
     0,     0,     1,    11,    29,     2,     6,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    23,    24,    25,    26,
    27,    28,    32,    33,    34,    35,    36,    37,    38,    39,
    40,    41,    42,    43,    44,    45,    46 ]

racc_action_pointer = [
    36,    52,    41,   nil,   nil,   nil,    56,   nil,   -18,    -2,
   nil,    40,   nil,    48,    49,    50,    51,    52,    53,    54,
    55,    56,   nil,    57,    58,    59,    60,    61,    62,    41,
   nil,    14,    55,    63,    57,    65,    65,    67,    62,    68,
    63,    64,    66,    66,    67,    68,    69,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil ]

racc_action_default = [
   -27,   -27,    -2,    -3,    -4,    -6,   -27,    -1,   -27,   -27,
    64,   -27,    -9,   -27,   -27,   -27,   -27,   -15,   -27,   -27,
   -27,   -27,   -20,   -27,   -27,   -27,   -27,   -27,   -27,   -27,
    -5,   -27,   -27,   -27,   -27,   -27,   -27,   -27,   -27,   -27,
   -27,   -27,   -27,   -27,   -27,   -27,   -27,    -7,    -8,   -10,
   -11,   -12,   -13,   -14,   -16,   -17,   -18,   -19,   -21,   -22,
   -23,   -24,   -25,   -26 ]

racc_goto_table = [
     3,     1,     7,    11,    29,     2,     8,     9,    48 ]

racc_goto_check = [
     3,     1,     3,     4,     4,     2,     5,     6,     7 ]

racc_goto_pointer = [
   nil,     1,     5,     0,    -5,     2,     2,   -23 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  0, 39, :_reduce_4,
  4, 36, :_reduce_5,
  0, 40, :_reduce_6,
  4, 37, :_reduce_none,
  3, 38, :_reduce_none,
  1, 38, :_reduce_none,
  3, 41, :_reduce_10,
  3, 41, :_reduce_11,
  3, 41, :_reduce_12,
  3, 41, :_reduce_13,
  3, 41, :_reduce_14,
  1, 41, :_reduce_15,
  3, 41, :_reduce_16,
  3, 41, :_reduce_17,
  3, 41, :_reduce_18,
  3, 41, :_reduce_19,
  1, 41, :_reduce_20,
  3, 41, :_reduce_21,
  3, 41, :_reduce_22,
  3, 41, :_reduce_23,
  3, 41, :_reduce_24,
  3, 41, :_reduce_25,
  3, 41, :_reduce_26 ]

racc_reduce_n = 27

racc_shift_n = 64

racc_token_table = {
  false => 0,
  :error => 1,
  "![[" => 2,
  "[[" => 3,
  "]]" => 4,
  "=" => 5,
  "/" => 6,
  :A1_NOTATION => 7,
  :END_MODIFIERS => 8,
  :EQ => 9,
  :HEX_COLOR => 10,
  :NUMBER => 11,
  :MODIFIER => 12,
  :MODIFIER_SEPARATOR => 13,
  :START_CELL_MODIFIERS => 14,
  :START_ROW_MODIFIERS => 15,
  :STRING => 16,
  :WORD => 17,
  "border" => 18,
  "bordercolor" => 19,
  "borderstyle" => 20,
  "color" => 21,
  "expand" => 22,
  "fontcolor" => 23,
  "fontfamily" => 24,
  "fontsize" => 25,
  "format" => 26,
  "freeze" => 27,
  "halign" => 28,
  "note" => 29,
  "numberformat" => 30,
  "validate" => 31,
  "valign" => 32,
  "var" => 33 }

racc_nt_base = 34

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"![[\"",
  "\"[[\"",
  "\"]]\"",
  "\"=\"",
  "\"/\"",
  "A1_NOTATION",
  "END_MODIFIERS",
  "EQ",
  "HEX_COLOR",
  "NUMBER",
  "MODIFIER",
  "MODIFIER_SEPARATOR",
  "START_CELL_MODIFIERS",
  "START_ROW_MODIFIERS",
  "STRING",
  "WORD",
  "\"border\"",
  "\"bordercolor\"",
  "\"borderstyle\"",
  "\"color\"",
  "\"expand\"",
  "\"fontcolor\"",
  "\"fontfamily\"",
  "\"fontsize\"",
  "\"format\"",
  "\"freeze\"",
  "\"halign\"",
  "\"note\"",
  "\"numberformat\"",
  "\"validate\"",
  "\"valign\"",
  "\"var\"",
  "$start",
  "modifiers_definition",
  "row_modifiers",
  "cell_modifiers",
  "modifiers",
  "@1",
  "@2",
  "modifier" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'modifier.y', 25)
  def _reduce_4(val, _values, result)
     parsing_row!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 27)
  def _reduce_5(val, _values, result)
     finished_row!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 29)
  def _reduce_6(val, _values, result)
     parsing_cell!
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

module_eval(<<'.,.,', 'modifier.y', 35)
  def _reduce_10(val, _values, result)
     modifier.border = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 36)
  def _reduce_11(val, _values, result)
     modifier.bordercolor = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 37)
  def _reduce_12(val, _values, result)
     modifier.borderstyle = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 38)
  def _reduce_13(val, _values, result)
     modifier.color = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 39)
  def _reduce_14(val, _values, result)
     modifier.expand = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 40)
  def _reduce_15(val, _values, result)
     modifier.expand!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 41)
  def _reduce_16(val, _values, result)
     modifier.fontcolor = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 42)
  def _reduce_17(val, _values, result)
     modifier.fontfamily = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 43)
  def _reduce_18(val, _values, result)
     modifier.fontsize = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 44)
  def _reduce_19(val, _values, result)
     modifier.format = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 45)
  def _reduce_20(val, _values, result)
     modifier.freeze!
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 46)
  def _reduce_21(val, _values, result)
     modifier.halign = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 47)
  def _reduce_22(val, _values, result)
     modifier.note = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 48)
  def _reduce_23(val, _values, result)
     modifier.numberformat = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 49)
  def _reduce_24(val, _values, result)
     modifier.validation = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 50)
  def _reduce_25(val, _values, result)
     modifier.valign = val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'modifier.y', 51)
  def _reduce_26(val, _values, result)
     define_var(val[2])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class ModifierParser
end   # module CSVPlusPlus
