#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require_relative '../lexer'

module CSVPlusPlus
  module Language
    class CellValueParser < Racc::Parser

module_eval(<<'...end cell_value.y/module_eval...', 'cell_value.y', 38)
  include ::CSVPlusPlus::Lexer

  protected

  def anything_to_parse?(input)
    input.strip.start_with?('=')
  end

  def parse_subject
    'cell value'
  end

  def return_value
    @ast
  end

  def tokenizer(input)
    ::CSVPlusPlus::Lexer::Tokenizer.new(
      catchall: /[\(\)\/\*\+\-,=&]/,
      ignore: /\s+/,
      input:,
      tokens: [
        [/true/i, :TRUE],
        [/false/i, :FALSE],
        [/"(?:[^"\\]|\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4}))*"/, :STRING],
        [/-?[\d.]+/, :NUMBER],
        [/\$\$/, :VAR_REF],
        [/[\$\w_]+/, :ID]
      ]
    )
  end
...end cell_value.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    18,    16,    10,     5,     8,     7,     9,     6,    10,     5,
     8,     7,     9,     6,    19,    10,     5,     8,     7,     9,
     6,     2,     3,    11,    12,    13,    14 ]

racc_action_check = [
    15,    13,     2,     2,     2,     2,     2,     2,    13,    13,
    13,    13,    13,    13,    15,    19,    19,    19,    19,    19,
    19,     0,     1,     3,     4,     5,     6 ]

racc_action_pointer = [
     5,    22,    -8,    23,    15,    23,    15,   nil,   nil,   nil,
   nil,   nil,   nil,    -2,   nil,    -3,   nil,   nil,   nil,     5,
   nil ]

racc_action_default = [
   -12,   -12,   -12,   -12,   -12,    -9,   -12,    -5,    -6,    -7,
    -8,    21,    -1,   -12,    -4,   -12,    -3,   -11,    -2,   -12,
   -10 ]

racc_goto_table = [
     4,     1,    15,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    17,   nil,   nil,   nil,   nil,   nil,    20 ]

racc_goto_check = [
     2,     1,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,    -2,   -11 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 19, :_reduce_1,
  4, 20, :_reduce_2,
  3, 20, :_reduce_3,
  2, 20, :_reduce_4,
  1, 20, :_reduce_5,
  1, 20, :_reduce_6,
  1, 20, :_reduce_7,
  1, 20, :_reduce_8,
  1, 20, :_reduce_9,
  3, 21, :_reduce_10,
  1, 21, :_reduce_11 ]

racc_reduce_n = 12

racc_shift_n = 21

racc_token_table = {
  false => 0,
  :error => 1,
  "(" => 2,
  ")" => 3,
  "&" => 4,
  "*" => 5,
  "/" => 6,
  "+" => 7,
  "-" => 8,
  :EOL => 9,
  :FALSE => 10,
  :ID => 11,
  :NUMBER => 12,
  :STRING => 13,
  :TRUE => 14,
  :VAR_REF => 15,
  "=" => 16,
  "," => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"(\"",
  "\")\"",
  "\"&\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "EOL",
  "FALSE",
  "ID",
  "NUMBER",
  "STRING",
  "TRUE",
  "VAR_REF",
  "\"=\"",
  "\",\"",
  "$start",
  "cell_value",
  "exp",
  "fn_call_args" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'cell_value.y', 17)
  def _reduce_1(val, _values, result)
     @ast = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 19)
  def _reduce_2(val, _values, result)
     result = e(:function_call, val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 20)
  def _reduce_3(val, _values, result)
     result = e(:function_call, val[0], [])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 21)
  def _reduce_4(val, _values, result)
     result = e(:variable, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 22)
  def _reduce_5(val, _values, result)
     result = e(:string, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 23)
  def _reduce_6(val, _values, result)
     result = e(:number, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 24)
  def _reduce_7(val, _values, result)
     result = e(:boolean, true)
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 25)
  def _reduce_8(val, _values, result)
     result = e(:boolean, false)
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 26)
  def _reduce_9(val, _values, result)
     result = e(:cell_reference, val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 28)
  def _reduce_10(val, _values, result)
     result = val[0] << val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'cell_value.y', 29)
  def _reduce_11(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class CellValueParser
  end   # module Language
end   # module CSVPlusPlus
